### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by richardvaldivieso** [yarbsemaj/sveltekit-adapter-lambda#42]
This is more a question than an issue. Is it possible to add extra functions with different VPN configurations in the serverless yml file? For example I have the following. Can I add the anotherFunction? So far it is not working for me
```yml
functions:
  #SSR Function
  svelte:
    handler: dist/server/serverless.handler
    memorySize: 256
    timeout: 15
    url: true
    package:
      individually: true
      exclude:
        - ./**
      include:
        - dist/server/**

  #Router Function
  cfLambda:
    handler: dist/edge/router.handler
    memorySize: 128
    timeout: 1
    # Set to '~' to disable the use of a VPC
    vpc: ~
    package:
      individually: true
      exclude:
        - ./**
      include:
        - dist/edge/**
    lambdaAtEdge:
      distribution: 'WebsiteDistribution'
      eventType: origin-request

anotherFunction:
    handler: entities/another.handler
```
